###Registrar el usuario
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba2",
    "email": "raul.paez@outlook.com",
    "password": "Pass_123"
}

### login sin conexion a BDD
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba2",
    "email": "raul.paez@outlook.com",
    "password": "Pass_123"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdWwucGFlekBvdXRsb29rLmNvbSIsImlkIjoxLCJpYXQiOjE3NDQyNTIwNzksImV4cCI6MTc0NDI1Mjk1OX0.T5wJGknzG-X4qbHokgor8kjReOUO_oau79Azt_V7VAQ